// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv6wAhj8aI3sZ7LN4ahvx6rnl_PE7nPWQ',
    appId: '1:431656219250:web:d78b4864c3e3e8a05608eb',
    messagingSenderId: '431656219250',
    projectId: 'beritadb',
    authDomain: 'beritadb.firebaseapp.com',
    storageBucket: 'beritadb.firebasestorage.app',
    measurementId: 'G-7YVS80NBBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAaSE5kDKbhnB4EARi-xrAcfdkpos99aY',
    appId: '1:431656219250:android:b3142721f04bc30b5608eb',
    messagingSenderId: '431656219250',
    projectId: 'beritadb',
    storageBucket: 'beritadb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR4BuuERd_KRzoD710qS-IXF__QBmgw9E',
    appId: '1:431656219250:ios:4c4d2592fe9b7e5b5608eb',
    messagingSenderId: '431656219250',
    projectId: 'beritadb',
    storageBucket: 'beritadb.firebasestorage.app',
    iosBundleId: 'com.example.listview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR4BuuERd_KRzoD710qS-IXF__QBmgw9E',
    appId: '1:431656219250:ios:4c4d2592fe9b7e5b5608eb',
    messagingSenderId: '431656219250',
    projectId: 'beritadb',
    storageBucket: 'beritadb.firebasestorage.app',
    iosBundleId: 'com.example.listview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv6wAhj8aI3sZ7LN4ahvx6rnl_PE7nPWQ',
    appId: '1:431656219250:web:8a515d0f611a190f5608eb',
    messagingSenderId: '431656219250',
    projectId: 'beritadb',
    authDomain: 'beritadb.firebaseapp.com',
    storageBucket: 'beritadb.firebasestorage.app',
    measurementId: 'G-JKLKHPK8ZW',
  );
}
